### ISSUE TITLE
Support for discrete non-numeric features/values

### ISSUE THREAD

**Issue by sandstrom** [apache/incubator-predictionio-template-attribute-based-classifier#1]
prediction-io is great, but it would be even better if one could use discrete, non-numeric features/values.

There also seems to be a few more with the same wish:
- https://groups.google.com/d/topic/predictionio-user/3N1X6w4q4z0/discussion
- https://groups.google.com/d/topic/predictionio-user/PmdqcOCN71o/discussion
- https://groups.google.com/d/topic/predictionio-user/zVQtk3aCyb4/discussion

**Comment by k4hoo** [comment]
Thanks for your suggestions! We are working on more examples for these.
meanwhile, you could also look at http://templates.prediction.io/repositories/10 which use categorical values as training data.

**Comment by Rainer-Kempkes** [comment]
hi, browsing through the PredictionIO template gallery there still seems to be no PredictionIo classifier for discrete non-numeric features, in which I am highly interested. Do you know any or can you provide me a hint how to do it for myself?

I tried to modify the DataSource.scala and Engine.scala but ran into errors. 
```
          LabeledPoint(properties.get[Double]("plan"),
            Vectors.dense(Array(
              properties.get[**String**]("attr0"),
              properties.get[**String**]("attr1"),
              properties.get[**String**]("attr2")
            ))
```
But pityfully it ain't that simple... :-(

regards,
Rainer

**Comment by sandstrom** [comment]
I'll close this. I think it's better to use spark, tensorflow or some other framework.
